Repository eclipse-zenoh/zenoh-python, pull requests merged in 2024-10, with the labels that each got.

#348 fix: remove varint implementation
  Cargo.lock
  Cargo.toml
  examples/z_bytes.py
  src/ext.rs
  tests/test_serializer.py
  zenoh/ext.py
  zenoh/ext.pyi
Labels: internal

#350 fix: wait longer on z_sub example
  tests/examples_check.py
Labels: internal

#354 Sync lockfile with Zenoh `e9f3b37` from `2024-10-08`
  Cargo.lock
  src/handlers.rs
Labels: internal

#355 chore: use new background internals
  .github/workflows/ci.yml
  Cargo.lock
  examples/z_pong.py
  examples/z_queryable.py
  examples/z_storage.py
  examples/z_sub.py
  examples/z_sub_thr.py
  src/handlers.rs
  src/macros.rs
  src/pubsub.rs
  src/query.rs
  src/scouting.rs
  src/session.rs
  tests/stubs_check.py
  zenoh/__init__.pyi
Labels: api sync, internal

#358 fix: revert callback entities to be background by default
  Cargo.lock
  examples/z_pong.py
  examples/z_queryable.py
  examples/z_storage.py
  examples/z_sub.py
  examples/z_sub_thr.py
  src/bytes.rs
  src/handlers.rs
  src/macros.rs
  src/pubsub.rs
  src/query.rs
  src/scouting.rs
  src/session.rs
  zenoh/__init__.pyi
Labels: enhancement

#351 fix: wait longer after z_put
  .github/workflows/ci.yml
  requirements-dev.txt
  tests/examples_check.py
Labels: internal

#365 fix: fix `Parameters.__iter__` not returning an iterator
  src/query.rs
Labels: bug

#366 feat: add warning if drop-callback is passed with a tuple
  src/handlers.rs
Labels: internal

#367 fix: fix typo in drop-callback warning
  src/handlers.rs
Labels: enhancement

#375 chore: revert ci check back to ubuntu-latest after isort fix
  .github/workflows/ci.yml
Labels: internal
