Repository eclipse-zenoh/zenoh-python, pull requests merged in 2024-09, with the labels that each got.

#301 chore: update pyproject.toml version to 1.0.0-dev
  pyproject.toml
Labels: bug

#308 feat!: remove reliability from subscriber
  Cargo.lock
  examples/z_pull.py
  examples/z_storage.py
  examples/z_sub.py
  examples/z_sub_queued.py
  examples/z_sub_thr.py
  src/pubsub.rs
  src/query.rs
  src/session.rs
  zenoh/__init__.pyi
Labels: breaking-change

#311 feat: add reliability to publisher
  Cargo.lock
  src/pubsub.rs
  src/session.rs
  zenoh/__init__.pyi
Labels: enhancement, new feature

#309 feat: add `ZBytes.serialize`
  examples/z_pub_thr.py
  src/bytes.rs
  src/macros.rs
  tests/test_serializer.py
  zenoh/__init__.pyi
Labels: enhancement

#312 docs: reformat example to put zenoh code first
  examples/z_delete.py
  examples/z_get.py
  examples/z_info.py
  examples/z_ping.py
  examples/z_pong.py
  examples/z_pub.py
  examples/z_pub_thr.py
  examples/z_pull.py
  examples/z_put.py
  examples/z_queryable.py
  examples/z_storage.py
  examples/z_sub.py
  examples/z_sub_queued.py
  examples/z_sub_thr.py
Labels: documentation

#313 refactor: use arcsession
  Cargo.lock
  Cargo.toml
  src/handlers.rs
  src/macros.rs
  src/pubsub.rs
  src/query.rs
  src/scouting.rs
  src/session.rs
  src/utils.rs
Labels: internal

#315 chore: update zenoh version
  Cargo.lock
  src/handlers.rs
Labels: api sync, internal

#316 Use init_log_from_env_or for examples
  examples/z_delete.py
  examples/z_get.py
  examples/z_info.py
  examples/z_ping.py
  examples/z_pong.py
  examples/z_pub.py
  examples/z_pub_thr.py
  examples/z_pull.py
  examples/z_put.py
  examples/z_queryable.py
  examples/z_scout.py
  examples/z_storage.py
  examples/z_sub.py
  examples/z_sub_queued.py
  examples/z_sub_thr.py
  src/lib.rs
  zenoh/__init__.pyi
Labels: enhancement

#320 feat: allow serializer overriding
  Cargo.toml
  examples/z_pub_thr.py
  src/bytes.rs
  src/utils.rs
  tests/test_override_serializer.py
  tests/test_serializer.py
  zenoh/__init__.pyi
Labels: enhancement, new feature

#323 fix: edit version for devel builds
  ci/scripts/bump-and-tag.bash
  requirements-dev.txt
Labels: internal

#326 fix: close if conditional
  ci/scripts/bump-and-tag.bash
Labels: internal

#327 fix: remove readonly from version
  ci/scripts/bump-and-tag.bash
Labels: internal

#322 feat: add wrapper types for all integer/float (de)serialization
  src/bytes.rs
  tests/test_serializer.py
  zenoh/__init__.py
  zenoh/__init__.pyi
Labels: enhancement

#329 chore: use new public config API
  Cargo.lock
  src/config.rs
  src/macros.rs
  src/query.rs
  src/session.rs
  zenoh/__init__.pyi
Labels: api sync, internal

#330 chore: API alignment
  .github/workflows/ci.yml
  src/lib.rs
  src/query.rs
  src/session.rs
  src/time.rs
  src/utils.rs
  zenoh/__init__.pyi
Labels: new feature, api sync

#333 feat: add protobuf into z_bytes example
  examples/entity.proto
  examples/z_bytes.py
Labels: documentation

#335 Align Rust with Reliability exported in zenoh::qos
  Cargo.lock
  src/lib.rs
  src/pubsub.rs
  src/qos.rs
  src/session.rs
Labels: internal

#342 chore: update release.yml for required labels
  .github/release.yml
Labels: internal
