Repository eclipse-zenoh/zenoh-python, pull requests merged in 2025-03, with the labels that each got.

#461 Query context manager
  examples/z_queryable.py
  src/handlers.rs
  src/query.rs
  src/utils.rs
  tests/examples_check.py
  zenoh/__init__.pyi
Labels: enhancement, new feature, api sync

#476 fix: update bump and tag for dev releases
  ci/scripts/bump-and-tag.bash
Labels: internal

#462 Bump Rust toolchain to 1.85
  rust-toolchain.toml
Labels: dependencies

#477 fix: add rust 1.75 CI check
  .github/workflows/ci.yml
Labels: internal

#491 document how to enable compilation feature in README
  README.md
Labels: documentation

#490 fix examples README outdated args
  examples/README.md
Labels: documentation
