Repository eclipse-zenoh/zenoh-python, pull requests merged in 2025-04, with the labels that each got.

#501 fix: can't pass socket address in cfg on python examples
  examples/common/common.py
Labels: bug

#510 Update z_ping.py
  examples/z_ping.py
Labels: bug

#504 style: fix few minor code style issues on examples
  examples/z_delete.py
  examples/z_get_liveliness.py
  examples/z_liveliness.py
  examples/z_ping.py
  examples/z_pong.py
  examples/z_pub.py
  examples/z_pull.py
  examples/z_put.py
  examples/z_put_float.py
  examples/z_sub.py
  examples/z_sub_liveliness.py
Labels: enhancement

#516 add Queryable.key_expr method
  Cargo.lock
  src/query.rs
  zenoh/__init__.pyi
Labels: enhancement, api sync
