Repository eclipse-zenoh/zenoh-python, pull requests merged in 2025-07, with the labels that each got.

#537 implement advanced pub/sub
  Cargo.toml
  docs/stubs_to_sources.py
  examples/z_advanced_pub.py
  examples/z_advanced_sub.py
  src/bytes.rs
  src/ext.rs
  src/lib.rs
  src/liveliness.rs
  src/macros.rs
  src/query.rs
  src/session.rs
  src/utils.rs
  tests/examples_check.py
  zenoh/__init__.pyi
  zenoh/ext.pyi
Labels: new feature, api sync

#553 add CongestionControl.BLOCK_FIRST
  Cargo.lock
  src/macros.rs
  src/qos.rs
  zenoh/__init__.pyi
Labels: new feature

#558 add locality and timestamp options
  src/ext.rs
  src/lib.rs
  src/pubsub.rs
  src/query.rs
  src/sample.rs
  src/session.rs
  zenoh/__init__.pyi
  zenoh/ext.pyi
Labels: enhancement, api sync

#554 [ZEN-587] Change `replier_id` type to `EntityGlobalId`
  Cargo.lock
  src/query.rs
  zenoh/__init__.pyi
Labels: api sync, breaking-change
